-- Сеть связей: координаты узлов и ручные связи между персонажами
-- Выполнить целиком в Supabase SQL Editor. Скрипт безопасно запускается повторно.

-- Координаты узла на карте связей (0–100, проценты от размеров сцены).
-- NULL = позиция вычисляется автоматически по кругу.
ALTER TABLE public.relationships
  ADD COLUMN IF NOT EXISTS pos_x double precision,
  ADD COLUMN IF NOT EXISTS pos_y double precision,
  ADD COLUMN IF NOT EXISTS group_tag text DEFAULT 'ally';
ALTER TABLE public.relationships ALTER COLUMN group_tag SET DEFAULT 'ally';

-- Комментарии-метки для наглядности в SQL Editor.
COMMENT ON COLUMN public.relationships.pos_x IS 'X-координата узла на карте 0..100 (NULL = авто)';
COMMENT ON COLUMN public.relationships.pos_y IS 'Y-координата узла на карте 0..100 (NULL = авто)';
COMMENT ON COLUMN public.relationships.group_tag IS 'Группа/круг: jedi, family, ally, sith, other';

-- Таблица ручных связей между персонажами (джедаи ↔ джедаи и т.п.).
-- Связи симметричные: хранится только одна запись (from_id < to_id).
-- Сера автоматически связывается со всеми — в этой таблице это не дублируется.
create table if not exists public.character_links (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  from_id bigint not null references public.relationships(id) on delete cascade,
  to_id   bigint not null references public.relationships(id) on delete cascade,
  link_type text default 'connection',
  note text,
  unique (from_id, to_id),
  constraint link_direction check (from_id < to_id)
);

alter table public.character_links enable row level security;

drop policy if exists "Public can read character_links" on public.character_links;
create policy "Public can read character_links" on public.character_links for select using (true);

drop policy if exists "Authenticated can insert character_links" on public.character_links;
create policy "Authenticated can insert character_links" on public.character_links for insert to authenticated with check (true);
drop policy if exists "Authenticated can update character_links" on public.character_links;
create policy "Authenticated can update character_links" on public.character_links for update to authenticated using (true) with check (true);
drop policy if exists "Authenticated can delete character_links" on public.character_links;
create policy "Authenticated can delete character_links" on public.character_links for delete to authenticated using (true);

-- Индекс для быстрой выборки всех связей конкретного персонажа.
create index if not exists character_links_from_idx on public.character_links(from_id);
create index if not exists character_links_to_idx   on public.character_links(to_id);
