-- Jedi Archives v7
-- Выполнить целиком в Supabase SQL Editor.
-- Скрипт безопасно запускается повторно.

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text,
  caption text,
  image_url text not null,
  sort_order integer not null default 0
);

alter table public.character enable row level security;
alter table public.chapters enable row level security;
alter table public.relationships enable row level security;
alter table public.gallery enable row level security;

drop policy if exists "Public can read character" on public.character;
create policy "Public can read character" on public.character for select using (true);
drop policy if exists "Public can read chapters" on public.chapters;
create policy "Public can read chapters" on public.chapters for select using (true);
drop policy if exists "Public can read relationships" on public.relationships;
create policy "Public can read relationships" on public.relationships for select using (true);
drop policy if exists "Public can read gallery" on public.gallery;
create policy "Public can read gallery" on public.gallery for select using (true);

drop policy if exists "Authenticated can insert character" on public.character;
create policy "Authenticated can insert character" on public.character for insert to authenticated with check (true);
drop policy if exists "Authenticated can update character" on public.character;
create policy "Authenticated can update character" on public.character for update to authenticated using (true) with check (true);
drop policy if exists "Authenticated can delete character" on public.character;
create policy "Authenticated can delete character" on public.character for delete to authenticated using (true);

drop policy if exists "Authenticated can insert chapters" on public.chapters;
create policy "Authenticated can insert chapters" on public.chapters for insert to authenticated with check (true);
drop policy if exists "Authenticated can update chapters" on public.chapters;
create policy "Authenticated can update chapters" on public.chapters for update to authenticated using (true) with check (true);
drop policy if exists "Authenticated can delete chapters" on public.chapters;
create policy "Authenticated can delete chapters" on public.chapters for delete to authenticated using (true);

drop policy if exists "Authenticated can insert relationships" on public.relationships;
create policy "Authenticated can insert relationships" on public.relationships for insert to authenticated with check (true);
drop policy if exists "Authenticated can update relationships" on public.relationships;
create policy "Authenticated can update relationships" on public.relationships for update to authenticated using (true) with check (true);
drop policy if exists "Authenticated can delete relationships" on public.relationships;
create policy "Authenticated can delete relationships" on public.relationships for delete to authenticated using (true);

drop policy if exists "Authenticated can insert gallery" on public.gallery;
create policy "Authenticated can insert gallery" on public.gallery for insert to authenticated with check (true);
drop policy if exists "Authenticated can update gallery" on public.gallery;
create policy "Authenticated can update gallery" on public.gallery for update to authenticated using (true) with check (true);
drop policy if exists "Authenticated can delete gallery" on public.gallery;
create policy "Authenticated can delete gallery" on public.gallery for delete to authenticated using (true);

-- Storage: создайте публичный bucket archive через Storage -> New bucket.
drop policy if exists "Public can read archive images" on storage.objects;
create policy "Public can read archive images" on storage.objects for select using (bucket_id = 'archive');
drop policy if exists "Authenticated can upload archive images" on storage.objects;
create policy "Authenticated can upload archive images" on storage.objects for insert to authenticated with check (bucket_id = 'archive');
drop policy if exists "Authenticated can update archive images" on storage.objects;
create policy "Authenticated can update archive images" on storage.objects for update to authenticated using (bucket_id = 'archive') with check (bucket_id = 'archive');
drop policy if exists "Authenticated can delete archive images" on storage.objects;
create policy "Authenticated can delete archive images" on storage.objects for delete to authenticated using (bucket_id = 'archive');
