-- Jedi Archives v7
-- Выполнить целиком в Supabase SQL Editor.
-- Скрипт безопасно запускается повторно.

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text,
  caption text,
  image_url text not null,
  sort_order integer not null default 0
);

alter table public.character enable row level security;
alter table public.chapters enable row level security;
alter table public.relationships enable row level security;
alter table public.gallery enable row level security;

drop policy if exists "Public can read character" on public.character;
create policy "Public can read character" on public.character for select using (true);
drop policy if exists "Public can read chapters" on public.chapters;
create policy "Public can read chapters" on public.chapters for select using (true);
drop policy if exists "Public can read relationships" on public.relationships;
create policy "Public can read relationships" on public.relationships for select using (true);
drop policy if exists "Public can read gallery" on public.gallery;
create policy "Public can read gallery" on public.gallery for select using (true);

drop policy if exists "Authenticated can insert character" on public.character;
create policy "Authenticated can insert character" on public.character for insert to authenticated with check (true);
drop policy if exists "Authenticated can update character" on public.character;
create policy "Authenticated can update character" on public.character for update to authenticated using (true) with check (true);
drop policy if exists "Authenticated can delete character" on public.character;
create policy "Authenticated can delete character" on public.character for delete to authenticated using (true);

drop policy if exists "Authenticated can insert chapters" on public.chapters;
create policy "Authenticated can insert chapters" on public.chapters for insert to authenticated with check (true);
drop policy if exists "Authenticated can update chapters" on public.chapters;
create policy "Authenticated can update chapters" on public.chapters for update to authenticated using (true) with check (true);
drop policy if exists "Authenticated can delete chapters" on public.chapters;
create policy "Authenticated can delete chapters" on public.chapters for delete to authenticated using (true);

drop policy if exists "Authenticated can insert relationships" on public.relationships;
create policy "Authenticated can insert relationships" on public.relationships for insert to authenticated with check (true);
drop policy if exists "Authenticated can update relationships" on public.relationships;
create policy "Authenticated can update relationships" on public.relationships for update to authenticated using (true) with check (true);
drop policy if exists "Authenticated can delete relationships" on public.relationships;
create policy "Authenticated can delete relationships" on public.relationships for delete to authenticated using (true);

-- Network metadata: manual node positions and direct links between
-- relationship records. The main character is connected to every node
-- automatically by the UI, so character_links only stores peer-to-peer links.
alter table public.relationships
  add column if not exists pos_x double precision,
  add column if not exists pos_y double precision,
  add column if not exists group_tag text default 'ally';
alter table public.relationships alter column group_tag set default 'ally';

create table if not exists public.character_links (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  from_id bigint not null references public.relationships(id) on delete cascade,
  to_id bigint not null references public.relationships(id) on delete cascade,
  link_type text not null default 'connection',
  note text,
  unique (from_id, to_id),
  constraint character_links_direction check (from_id < to_id)
);

alter table public.character_links enable row level security;
drop policy if exists "Public can read character_links" on public.character_links;
create policy "Public can read character_links" on public.character_links for select using (true);
drop policy if exists "Authenticated can insert character_links" on public.character_links;
create policy "Authenticated can insert character_links" on public.character_links for insert to authenticated with check (true);
drop policy if exists "Authenticated can update character_links" on public.character_links;
create policy "Authenticated can update character_links" on public.character_links for update to authenticated using (true) with check (true);
drop policy if exists "Authenticated can delete character_links" on public.character_links;
create policy "Authenticated can delete character_links" on public.character_links for delete to authenticated using (true);
create index if not exists character_links_from_idx on public.character_links(from_id);
create index if not exists character_links_to_idx on public.character_links(to_id);

drop policy if exists "Authenticated can insert gallery" on public.gallery;
create policy "Authenticated can insert gallery" on public.gallery for insert to authenticated with check (true);
drop policy if exists "Authenticated can update gallery" on public.gallery;
create policy "Authenticated can update gallery" on public.gallery for update to authenticated using (true) with check (true);
drop policy if exists "Authenticated can delete gallery" on public.gallery;
create policy "Authenticated can delete gallery" on public.gallery for delete to authenticated using (true);

-- Storage: создайте публичный bucket archive через Storage -> New bucket.
drop policy if exists "Public can read archive images" on storage.objects;
create policy "Public can read archive images" on storage.objects for select using (bucket_id = 'archive');
drop policy if exists "Authenticated can upload archive images" on storage.objects;
create policy "Authenticated can upload archive images" on storage.objects for insert to authenticated with check (bucket_id = 'archive');
drop policy if exists "Authenticated can update archive images" on storage.objects;
create policy "Authenticated can update archive images" on storage.objects for update to authenticated using (bucket_id = 'archive') with check (bucket_id = 'archive');
drop policy if exists "Authenticated can delete archive images" on storage.objects;
create policy "Authenticated can delete archive images" on storage.objects for delete to authenticated using (bucket_id = 'archive');
