import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{BrowserRouter,Routes,Route,Link,NavLink,useNavigate}from'react-router-dom';
import{ArrowRight,BookOpen,ChevronRight,Database,Image as ImageIcon,LogIn,Menu,Shield,UserRound,X,Save,Trash2,Plus,Upload,RefreshCw,Lock,Terminal,Images,Edit3,Eye,EyeOff}from'lucide-react';
import{createClient}from'@supabase/supabase-js';
import'./styles.css';

const SUPA_URL=import.meta.env.VITE_SUPABASE_URL;
const SUPA_KEY=import.meta.env.VITE_SUPABASE_ANON_KEY;
const STORAGE_BUCKET=import.meta.env.VITE_SUPABASE_STORAGE_BUCKET||'archive';
const supabase=SUPA_URL&&SUPA_KEY?createClient(SUPA_URL,SUPA_KEY):null;

const fallback={id:1,name:'Сера Аверн',first_name:'Сера',last_name:'Аверн',species:'Сквиб',age:3,height:72,homeworld:'Скор II',status:'Джедай-юнлинг',callsign:'—',summary:'Чувствительный к Силе сквиб, происходящий со Скор II. В настоящее время проходит раннее обучение в Ордене Джедаев.',appearance:'Тело покрыто густой, мягкой шерстью почти угольно-чёрного окраса. Крупные чуткие уши значительно выделяются даже для его вида, а большие янтарно-золотистые глаза постоянно выдают любопытство и настороженность.',personality:'Любопытный, активный и эмоциональный ребёнок. Сера легко идёт на контакт, любит наблюдать за окружающими и плохо переносит скуку. Он не тихий и не замкнутый: если ему что-то интересно, об этом быстро узнают все вокруг.',preferences:'Нравятся животные, механизмы, новые места, игры и всё, что можно исследовать. Особенно любит занятия, где разрешено двигаться и что-нибудь делать своими лапами.',dislikes:'Не любит долго сидеть без дела, резкие звуки, грубость и ситуации, в которых взрослые намеренно скрывают от него что-то важное.',motivation:'Понять окружающий мир, научиться управлять своей чувствительностью к Силе и доказать себе, что он способен стать настоящим джедаем.',image_url:'',holo_effect:true};
const fallbackChapters=[{id:'local-1',chapter_number:1,title:'Ребёнок со Скор II',content:'Сера Аверн родился на Скор II, среди лесов и поселений, где жизнь была гораздо спокойнее, чем на большинстве крупных миров Республики. Его семья жила простой жизнью, стараясь дать ребёнку возможность расти без лишних забот. С ранних лет Сера отличался необычной внимательностью: он замечал звуки раньше других, чувствовал приближение людей и иногда реагировал на события ещё до того, как они происходили.\n\nОн рос активным и любопытным ребёнком. Его интересовало практически всё вокруг — от животных и растений до механизмов и работы взрослых. Сера не любил просто наблюдать издалека: если что-то привлекало его внимание, он стремился подойти ближе и разобраться самостоятельно.\n\nПостепенно родители начали замечать, что некоторые особенности сына невозможно объяснить одной лишь детской наблюдательностью.',cover_image:'',published:true},{id:'local-2',chapter_number:2,title:'Когда пришёл джедай',content:'Когда Сере исполнилось три года, на Скор II прибыл джедай Кайрен Валь. Его визит не был случайностью: Орден получил сведения о ребёнке, чья связь с Силой могла проявляться необычным образом.\n\nКайрен не спешил забирать Серу силой или пугать его рассказами об Ордене. Он сначала познакомился с семьёй, наблюдал за ребёнком и позволил ему самому проявить интерес. Сера быстро начал рассматривать незнакомого джедая с таким же любопытством, с каким обычно изучал новые механизмы.\n\nПосле проверки стало ясно, что чувствительность Серы к Силе действительно достаточно сильна, чтобы Орден предложил ему обучение. Вскоре Сера покинул Скор II вместе с Кайреном Валь.',cover_image:'',published:true}];
const fallbackRelations=[{id:'local-r1',name:'Рен Аверн',role:'Отец',relation:'Любовь',quote:'Сначала разберёмся, что сломалось. Потом решим, как это чинить.'},{id:'local-r2',name:'Лира Аверн',role:'Мать',relation:'Любовь',quote:'Не обязательно всё понимать сразу. Главное — не переставай задавать вопросы.'},{id:'local-r3',name:'Кайрен Валь',role:'Джедай, забравший Серу',relation:'Уважение',quote:'Сила не делает тебя взрослым. Она лишь учит внимательнее слушать мир.'}];

const clean=v=>v===null||v===undefined||v===''?'—':v;
const ageText=v=>{const n=Number(v);if(!Number.isFinite(n))return clean(v);return `${n} ${n===1?'стандартный год':n>=2&&n<=4?'стандартных года':'стандартных лет'}`};
const heightText=v=>{const n=Number(v);return Number.isFinite(n)?`${n} см`:clean(v)};
function displayCharacter(row){
 if(!row)return fallback;
 let name=String(row.name||'').trim();
 const first=String(row.first_name||'').trim(),last=String(row.last_name||'').trim();
 if((!name||name.toLowerCase()==='сера')&&first&&last)name=`${first} ${last}`;
 if(!name)name=fallback.name;
 return{...fallback,...row,name};
}

function useArchive(){
 const[c,setC]=useState(supabase?null:fallback),[ch,setCh]=useState(supabase?[]:fallbackChapters),[r,setR]=useState(supabase?[]:fallbackRelations),[g,setG]=useState([]),[loading,setLoading]=useState(!!supabase),[error,setError]=useState('');
 const load=async()=>{
  if(!supabase){setLoading(false);return}
  setLoading(true);setError('');
  try{
   const results=await Promise.all([
    supabase.from('character').select('*').order('id').limit(1),
    supabase.from('chapters').select('*').order('chapter_number'),
    supabase.from('relationships').select('*').order('id'),
    supabase.from('gallery').select('*').order('created_at',{ascending:false})
   ]);
   const[a,b,d,gal]=results;
   if(a.error)throw a.error;if(b.error)throw b.error;if(d.error)throw d.error;
   setC(a.data?.[0]?displayCharacter(a.data[0]):null);
   setCh(Array.isArray(b.data)?b.data:[]);
   setR(Array.isArray(d.data)?d.data:[]);
   if(gal.error) throw gal.error;
   setG(Array.isArray(gal.data)?gal.data:[]);
  }catch(e){setError(e.message||'Не удалось загрузить архив.')}finally{setLoading(false)}
 };
 useEffect(()=>{load()},[]);
 return{character:c,chapters:ch,relationships:r,gallery:g,loading,error,reload:load,setCharacter:setC,setChapters:setCh,setRelationships:setR,setGallery:setG};
}

function Background(){return <><div className="hud-grid"/><div className="hud-bars"><i/><i/><i/><i/></div><div className="scanline"/></>}
function Layout({children}){const[open,setOpen]=useState(false);const links=[['/','Главная'],['/character','Персонаж'],['/history','История'],['/relationships','Взаимоотношения'],['/gallery','Галерея']];return <div className="shell"><Background/><header className="topbar"><Link className="brand" to="/"><b>✦</b> JEDI ARCHIVES</Link><button className="mobile" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{links.map(([to,l])=><NavLink key={to} to={to} onClick={()=>setOpen(false)}>{l}</NavLink>)}</nav></header><main>{children}</main><footer><span>ОРДЕН ДЖЕДАЕВ // АРХИВ</span><span>ID АРХИВА // SA-001</span><Link to="/admin">СЛУЖЕБНЫЙ ДОСТУП</Link></footer></div>}
function Data({label,value}){return <div className="data-row"><span>{label}</span><strong>{clean(value)}</strong></div>}
function Page({title,sub,children}){return <section className="page"><div className="heading holo-panel"><div><p className="kicker">{sub}</p><h1>{title}</h1></div><span className="chip">● АРХИВ АКТИВЕН</span></div>{children}</section>}
function Holo({children,className=''}){return <div className={`holo-panel ${className}`}>{children}</div>}
function Home({c,ch}){if(!c)return <Page title="Архив пуст" sub="DATABASE // NO RECORD"><Holo className="empty"><Database/><p>В таблице character нет записи. Добавьте персонажа через админ-панель.</p></Holo></Page>;const parts=String(c.name||'').trim().split(/\s+/);const first=parts[0]||'Сера',last=parts.slice(1).join(' ')||'Аверн';return <><section className="hero"><Holo className="hero-copy"><div className="headerline"><span>JEDI ORDER // ARCHIVES</span><span className="status">ЗАПИСЬ АКТИВНА</span></div><p className="kicker">ЛИЧНОЕ ДЕЛО</p><h1>{first}<small>{last}</small></h1><div className="line"/><p className="lead">{c.summary}</p><div className="griddata"><Data label="РАСА" value={c.species}/><Data label="ВОЗРАСТ" value={ageText(c.age)}/><Data label="РОСТ" value={heightText(c.height)}/><Data label="РОДНОЙ МИР" value={c.homeworld}/><Data label="СТАТУС" value={c.status}/><Data label="ПОЗЫВНОЙ" value={c.callsign}/></div><Link className="btn" to="/character">ОТКРЫТЬ ДОСЬЕ <ArrowRight size={17}/></Link><div className="panel-footer"><span>ARCHIVE ID // SA-001</span><span>JEDI TEMPLE DATABASE</span></div></Holo><Holo className="hero-photo">{c.image_url?<img className={c.holo_effect!==false?"holo-image":""} src={c.image_url} alt={c.name}/>:<div className="placeholder"><ImageIcon/><span>ИЗОБРАЖЕНИЕ НЕ ЗАГРУЖЕНО</span></div>}<small>СКОР II // АРХИВ ХРАМА ДЖЕДАЕВ</small></Holo></section><section className="cards"><Card icon={<BookOpen/>} title="История" text="Жизненный путь Серы до обучения в Ордене." to="/history"/><Card icon={<UserRound/>} title="Взаимоотношения" text="Люди, сыгравшие важную роль в его жизни." to="/relationships"/><Card icon={<Database/>} title="Архив" text={`${ch.length} ${ch.length===1?'глава':'главы'} в текущем архиве.`} to="/character"/></section></>}
function Card({icon,title,text,to}){return <Link className="card" to={to}><div className="card-icon">{icon}</div><span><b>{title}</b><small>{text}</small></span><ChevronRight/></Link>}
function Character({c}){if(!c)return <Page title="Персонаж" sub="ЛИЧНОЕ ДЕЛО"><Holo className="empty"><Database/><p>Запись персонажа отсутствует в базе данных.</p></Holo></Page>;const sections=[['Внешность',c.appearance],['Характер',c.personality],['Предпочтения и симпатии',c.preferences],['Антипатии и избегания',c.dislikes],['Мотивация',c.motivation]];return <Page title="Персонаж" sub="ЛИЧНОЕ ДЕЛО // SA-001"><div className="profile"><Holo className="profile-card"><div className="portrait">{c.image_url?<img className={c.holo_effect!==false?"holo-image":""} src={c.image_url} alt={c.name}/>:<div className="placeholder"><ImageIcon/></div>}</div><div className="bio"><p className="kicker">АРХИВ ОРДЕНА ДЖЕДАЕВ</p><h2>{c.name}</h2><div className="data-block"><Data label="РАСА" value={c.species}/><Data label="ВОЗРАСТ" value={ageText(c.age)}/><Data label="РОСТ" value={heightText(c.height)}/><Data label="РОДНОЙ МИР" value={c.homeworld}/><Data label="СТАТУС" value={c.status}/><Data label="ПОЗЫВНОЙ" value={c.callsign}/></div></div></Holo><div className="texts">{sections.map(([a,b])=><Holo className="text-panel" key={a}><h2>{a}</h2><div className="section-line"/><p>{b||'Запись отсутствует.'}</p></Holo>)}</div></div></Page>}
function History({ch}){const visible=ch.filter(x=>x.published!==false).sort((a,b)=>(a.chapter_number??0)-(b.chapter_number??0));return <Page title="История" sub="ХРОНОЛОГИЯ // РАННИЕ ГОДЫ"><div className="timeline">{visible.map((x,i)=><article className="chapter" key={x.id}><div className="marker">{String(x.chapter_number||i+1).padStart(2,'0')}</div><Holo className="chapter-panel"><p className="kicker">ГЛАВА {x.chapter_number||i+1}</p><h2>{x.title}</h2><div className="section-line"/>{x.cover_image&&<img src={x.cover_image} alt=""/>}{String(x.content||'').split(/\n+/).filter(Boolean).map((p,j)=><p key={j}>{p}</p>)}</Holo></article>)}</div></Page>}
function Relationships({r}){return <Page title="Взаимоотношения" sub="ЛИЧНЫЕ СВЯЗИ // РАННИЙ ПЕРИОД"><div className="relations">{r.map(x=><Holo className="relation" key={x.id}>{x.image_url?<img className={`relation-photo ${x.holo_effect!==false?"holo-image":""}`} src={x.image_url} alt={x.name}/>:<div className="avatar">{String(x.name||'?')[0]}</div>}<div><p className="kicker">{x.role}</p><h2>{x.name}</h2><span>{x.relation}</span>{x.quote&&<blockquote>«{x.quote}»</blockquote>}</div></Holo>)}</div></Page>}
function Gallery({c,gallery}){const items=gallery.length?gallery:(c?.image_url?[{id:'main',image_url:c.image_url,title:'Основной портрет',caption:`PERSONNEL // ${c.name}`}]:[]);return <Page title="Галерея" sub="ВИЗУАЛЬНЫЙ АРХИВ"><div className="gallery">{items.length?items.map(x=><figure className="holo-panel" key={x.id}><img src={x.image_url||x.url} alt={x.title||x.caption||''}/><figcaption>{x.caption||x.title||'АРХИВНЫЙ МАТЕРИАЛ'}</figcaption></figure>):<Holo className="empty"><Images/><p>Изображения появятся здесь после загрузки.</p></Holo>}</div></Page>}
function AdminLogin(){const nav=useNavigate();const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false);const login=async e=>{e.preventDefault();if(!supabase){setErr('Supabase не подключён. Проверьте .env.');return}setBusy(true);setErr('');const normalized=email.trim().includes('@')?email.trim():email.trim()+'@jedi-archives.local';const{error}=await supabase.auth.signInWithPassword({email:normalized,password});if(error)setErr('Не удалось войти. Проверьте логин и пароль.');else nav('/admin/panel');setBusy(false)};return <Page title="Админ-панель" sub="ЗАЩИЩЁННЫЙ ДОСТУП"><Holo className="login"><Shield size={28}/><p className="kicker">SECURITY GATE // LEVEL 5</p><h2>ЗАКРЫТЫЙ АРХИВ</h2><p>Доступ к редактированию базы разрешён только авторизованному пользователю.</p><form onSubmit={login}><label>ЛОГИН<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="tenkara" autoComplete="username" required/></label><label>ПАРОЛЬ<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label><button className="btn" disabled={busy}><LogIn size={17}/> {busy?'ПРОВЕРКА…':'ВОЙТИ В АРХИВ'}</button>{err&&<em>{err}</em>}</form></Holo></Page>}
function AdminGuard({children}){const[s,setS]=useState(undefined);useEffect(()=>{if(!supabase){setS(null);return}supabase.auth.getSession().then(({data})=>setS(data.session));const{data}=supabase.auth.onAuthStateChange((_,session)=>setS(session));return()=>data.subscription.unsubscribe()},[]);if(s===undefined)return <Page title="Панель" sub="ПРОВЕРКА ДОСТУПА"><div className="loading">ПРОВЕРКА СЕССИИ…</div></Page>;return s?children:<AdminLogin/>}

function AdminPanel({archive}){
 const{character,chapters,relationships,reload}=archive;const[tab,setTab]=useState('character');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[form,setForm]=useState(character);const[chForm,setChForm]=useState({id:null,chapter_number:'',title:'',content:'',cover_image:'',published:true});const[relForm,setRelForm]=useState({id:null,name:'',role:'',relation:'',quote:'',image_url:'',holo_effect:true});
 const[galForm,setGalForm]=useState({id:null,title:'',image_url:'',description:'',holo_effect:true});
 useEffect(()=>setForm(character||fallback),[character]);
 const run=async(fn,success)=>{setBusy(true);setMsg('');try{const{error}=await fn();if(error)throw error;setMsg(success);await reload()}catch(e){setMsg('Ошибка: '+(e.message||e))}finally{setBusy(false)}};
 const saveCharacter=async e=>{e.preventDefault();const payload={name:String(form.name||'').trim(),first_name:String(form.name||'').trim().split(/\s+/)[0]||'',last_name:String(form.name||'').trim().split(/\s+/).slice(1).join(' ')||'',species:form.species||'',age:Number(form.age),height:Number(form.height),homeworld:form.homeworld||'',status:form.status||'',callsign:form.callsign||'',summary:form.summary||'',appearance:form.appearance||'',personality:form.personality||'',preferences:form.preferences||'',dislikes:form.dislikes||'',motivation:form.motivation||'',image_url:form.image_url||''};return run(async()=>{if(character?.id){const res=await supabase.from('character').update(payload).eq('id',character.id).select();if(res.error)throw res.error;if(!res.data?.length)throw new Error('Запись character не найдена или обновление запрещено RLS.')}else{const res=await supabase.from('character').insert(payload).select();if(res.error)throw res.error;if(!res.data?.length)throw new Error('Не удалось создать запись character.')}},'Данные персонажа сохранены в Supabase.')};
 const saveChapter=e=>{e.preventDefault();const payload={chapter_number:Number(chForm.chapter_number),title:chForm.title,content:chForm.content,cover_image:chForm.cover_image||'',published:chForm.published};return run(()=>chForm.id?supabase.from('chapters').update(payload).eq('id',chForm.id):supabase.from('chapters').insert(payload),chForm.id?'Глава обновлена.':'Глава добавлена.')};
 const saveRelation=e=>{e.preventDefault();const payload={name:relForm.name,role:relForm.role,relation:relForm.relation,quote:relForm.quote,image_url:relForm.image_url||'',holo_effect:relForm.holo_effect!==false};return run(()=>relForm.id?supabase.from('relationships').update(payload).eq('id',relForm.id):supabase.from('relationships').insert(payload),relForm.id?'Связь обновлена.':'Связь добавлена.')};
 const remove=(table,id,label)=>{if(!confirm(`Удалить ${label}?`))return;return run(()=>supabase.from(table).delete().eq('id',id),`${label[0].toUpperCase()+label.slice(1)} удалена.`)};
 const uploadFile=async(file,folder='archive')=>{if(!file||!supabase)return '';const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${folder||'archive'}/${Date.now()}.${ext}`;const up=await supabase.storage.from(STORAGE_BUCKET).upload(path,file,{upsert:false,contentType:file.type});if(up.error)throw up.error;return supabase.storage.from(STORAGE_BUCKET).getPublicUrl(path).data.publicUrl};
 const upload=async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{const url=await uploadFile(file,'character');setForm(f=>({...f,image_url:url}));setMsg('Изображение загружено. Нажмите «Сохранить».')}catch(e){setMsg('Ошибка Storage: '+e.message)}finally{setBusy(false)}};
 const uploadRelation=async e=>{const file=e.target.files?.[0];if(!file)return;try{const url=await uploadFile(file,'relationships');setRelForm(f=>({...f,image_url:url}))}catch(e){setMsg('Ошибка Storage: '+e.message)}};
 const uploadGallery=async e=>{const file=e.target.files?.[0];if(!file)return;try{const url=await uploadFile(file,'gallery');setGalForm(f=>({...f,image_url:url}))}catch(e){setMsg('Ошибка Storage: '+e.message)}};
 const deleteGallery=async(item)=>{if(!confirm('Удалить изображение?'))return;try{const path=item.image_url?.split('/'+STORAGE_BUCKET+'/')[1];if(path) await supabase.storage.from(STORAGE_BUCKET).remove([path]);await supabase.from('gallery').delete().eq('id',item.id);reload();setMsg('Изображение удалено.')}catch(e){setMsg('Ошибка удаления: '+e.message)}};
 const logout=()=>supabase.auth.signOut();
 const resetChapter=()=>setChForm({id:null,chapter_number:'',title:'',content:'',cover_image:'',published:true});const resetRelation=()=>setRelForm({id:null,name:'',role:'',relation:'',quote:'',image_url:'',holo_effect:true});
 return <Page title="Панель управления" sub="АДМИНИСТРАТОР // ДОСТУП РАЗРЕШЁН"><div className="admin-top"><span><span className="pulse">●</span> ДОСТУП РАЗРЕШЁН</span><div><button className="ghost" onClick={reload}><RefreshCw size={14}/> ОБНОВИТЬ</button><button className="ghost" onClick={logout}><Lock size={14}/> ВЫЙТИ</button></div></div><div className="admin-tabs"><button className={tab==='character'?'active':''} onClick={()=>setTab('character')}><UserRound/> ПЕРСОНАЖ</button><button className={tab==='chapters'?'active':''} onClick={()=>setTab('chapters')}><BookOpen/> ГЛАВЫ</button><button className={tab==='relations'?'active':''} onClick={()=>setTab('relations')}><Database/> СВЯЗИ</button><button className={tab==='gallery'?'active':''} onClick={()=>setTab('gallery')}><Images/> ГАЛЕРЕЯ</button></div>{msg&&<div className="toast">{msg}</div>}
 {tab==='character'&&<Holo className="editor"><div className="editor-head"><div><p className="kicker">PERSONNEL RECORD // SA-001</p><h2>СЕРА АВЕРН</h2></div><Save/></div><form onSubmit={saveCharacter}><div className="form-grid"><Field label="Имя и фамилия" value={form.name} onChange={v=>setForm({...form,name:v})}/><Field label="Раса" value={form.species} onChange={v=>setForm({...form,species:v})}/><Field label="Возраст (число)" type="number" value={form.age} onChange={v=>setForm({...form,age:v})}/><Field label="Рост (см)" type="number" value={form.height} onChange={v=>setForm({...form,height:v})}/><Field label="Родной мир" value={form.homeworld} onChange={v=>setForm({...form,homeworld:v})}/><Field label="Статус" value={form.status} onChange={v=>setForm({...form,status:v})}/><Field label="Позывной" value={form.callsign} onChange={v=>setForm({...form,callsign:v})}/><div className="field"><label>Основная фотография</label><div className="upload"><input value={form.image_url||''} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="URL изображения"/><label className="upload-btn"><Upload size={14}/> ЗАГРУЗИТЬ<input type="file" accept="image/*" onChange={upload}/></label></div></div></div><TextField label="Краткое описание" value={form.summary} onChange={v=>setForm({...form,summary:v})}/><TextField label="Внешность" value={form.appearance} onChange={v=>setForm({...form,appearance:v})}/><TextField label="Характер" value={form.personality} onChange={v=>setForm({...form,personality:v})}/><TextField label="Предпочтения и симпатии" value={form.preferences} onChange={v=>setForm({...form,preferences:v})}/><TextField label="Антипатии и избегания" value={form.dislikes} onChange={v=>setForm({...form,dislikes:v})}/><TextField label="Мотивация" value={form.motivation} onChange={v=>setForm({...form,motivation:v})}/><button className="btn" disabled={busy}><Save size={16}/> СОХРАНИТЬ В БАЗУ</button></form></Holo>}
 {tab==='chapters'&&<div className="admin-columns"><Holo className="editor"><div className="editor-head"><div><p className="kicker">CONTENT MANAGEMENT</p><h2>{chForm.id?'РЕДАКТИРОВАНИЕ ГЛАВЫ':'НОВАЯ ГЛАВА'}</h2></div>{chForm.id?<Edit3/>:<Plus/>}</div><form onSubmit={saveChapter}><div className="form-grid"><Field label="Номер главы" type="number" value={chForm.chapter_number} onChange={v=>setChForm({...chForm,chapter_number:v})}/><Field label="Название" value={chForm.title} onChange={v=>setChForm({...chForm,title:v})}/></div><TextField label="Текст главы" value={chForm.content} onChange={v=>setChForm({...chForm,content:v})}/><Field label="URL обложки" value={chForm.cover_image} onChange={v=>setChForm({...chForm,cover_image:v})}/><label className="check"><input type="checkbox" checked={chForm.published} onChange={e=>setChForm({...chForm,published:e.target.checked})}/> Публиковать главу</label><div className="editor-actions"><button className="btn" disabled={busy}>{chForm.id?<><Save size={16}/> СОХРАНИТЬ ИЗМЕНЕНИЯ</>:<><Plus size={16}/> ДОБАВИТЬ ГЛАВУ</>}</button>{chForm.id&&<button type="button" className="ghost" onClick={resetChapter}>ОТМЕНА</button>}</div></form></Holo><div className="list">{chapters.map(x=><Holo className="list-item" key={x.id}><div><span className="list-number">{String(x.chapter_number).padStart(2,'0')}</span><div><b>{x.title}</b><small>{x.published===false?'СКРЫТА':'ОПУБЛИКОВАНА'}</small></div></div><div className="item-actions"><button className="ghost" onClick={()=>setChForm({id:x.id,chapter_number:x.chapter_number,title:x.title||'',content:x.content||'',cover_image:x.cover_image||'',published:x.published!==false})}><Edit3 size={14}/></button><button className="danger" onClick={()=>remove('chapters',x.id,'главу')}><Trash2 size={15}/></button></div></Holo>)}</div></div>}
 {tab==='relations'&&<div className="admin-columns"><Holo className="editor"><div className="editor-head"><div><p className="kicker">RELATIONSHIP DATABASE</p><h2>{relForm.id?'РЕДАКТИРОВАНИЕ СВЯЗИ':'НОВАЯ СВЯЗЬ'}</h2></div>{relForm.id?<Edit3/>:<Plus/>}</div><form onSubmit={saveRelation}><Field label="Имя" value={relForm.name} onChange={v=>setRelForm({...relForm,name:v})}/><Field label="Роль" value={relForm.role} onChange={v=>setRelForm({...relForm,role:v})}/><Field label="Отношение" value={relForm.relation} onChange={v=>setRelForm({...relForm,relation:v})}/><TextField label="Цитата" value={relForm.quote} onChange={v=>setRelForm({...relForm,quote:v})}/><div className="field"><label>Фотография связи</label><label className="upload-btn"><Upload size={14}/> ЗАГРУЗИТЬ<input type="file" accept="image/*" onChange={uploadRelation}/></label>{relForm.image_url&&<img className="holo-thumb holo-image" src={relForm.image_url}/>}<label className="check"><input type="checkbox" checked={relForm.holo_effect!==false} onChange={e=>setRelForm({...relForm,holo_effect:e.target.checked})}/> Голопроекция</label></div><div className="editor-actions"><button className="btn" disabled={busy}>{relForm.id?<><Save size={16}/> СОХРАНИТЬ ИЗМЕНЕНИЯ</>:<><Plus size={16}/> ДОБАВИТЬ СВЯЗЬ</>}</button>{relForm.id&&<button type="button" className="ghost" onClick={resetRelation}>ОТМЕНА</button>}</div></form></Holo><div className="list">{relationships.map(x=><Holo className="list-item" key={x.id}><div><span className="avatar mini">{String(x.name||'?')[0]}</span><div><b>{x.name}</b><small>{x.role} // {x.relation}</small></div></div><div className="item-actions"><button className="ghost" onClick={()=>setRelForm({id:x.id,name:x.name||'',role:x.role||'',relation:x.relation||'',quote:x.quote||'',image_url:x.image_url||'',holo_effect:x.holo_effect!==false})}><Edit3 size={14}/></button><button className="danger" onClick={()=>remove('relationships',x.id,'связь')}><Trash2 size={15}/></button></div></Holo>)}</div></div>}
 {tab==='gallery'&&<div className="admin-columns"><Holo className="editor"><div className="editor-head"><h2>НОВОЕ ИЗОБРАЖЕНИЕ</h2><Images/></div><form onSubmit={e=>{e.preventDefault();run(()=>supabase.from('gallery').insert({title:galForm.title,description:galForm.description,image_url:galForm.image_url,holo_effect:galForm.holo_effect!==false}),'Изображение добавлено.')}}><Field label="Название" value={galForm.title} onChange={v=>setGalForm({...galForm,title:v})}/><Field label="Описание" value={galForm.description} onChange={v=>setGalForm({...galForm,description:v})}/><label className="upload-btn"><Upload size={14}/> ЗАГРУЗИТЬ<input type="file" accept="image/*" onChange={uploadGallery}/></label>{galForm.image_url&&<img className="holo-thumb holo-image" src={galForm.image_url}/>}<label className="check"><input type="checkbox" checked={galForm.holo_effect!==false} onChange={e=>setGalForm({...galForm,holo_effect:e.target.checked})}/> Голопроекция</label><button className="btn"><Save/> СОХРАНИТЬ</button></form></Holo><div className="list">{archive.gallery.map(x=><Holo className="list-item" key={x.id}><div><b>{x.title}</b>{x.image_url&&<img className={`holo-thumb ${x.holo_effect!==false?"holo-image":""}`} src={x.image_url}/>}</div><button className="danger" onClick={()=>deleteGallery(x)}><Trash2 size={15}/></button></Holo>)}</div></div>}
 <div className="admin-foot"><Terminal size={14}/> ИСТОЧНИК ДАННЫХ: SUPABASE // Данные отображаются напрямую из Supabase. Возраст и рост хранятся числами и форматируются интерфейсом.</div></Page>
}
function Field({label,value,onChange,type='text'}){return <div className="field"><label>{label}</label><input type={type} value={value??''} onChange={e=>onChange(e.target.value)}/></div>}
function TextField({label,value,onChange}){return <div className="field"><label>{label}</label><textarea rows="5" value={value??''} onChange={e=>onChange(e.target.value)}/></div>}
function App(){const archive=useArchive();return <Layout><Routes><Route path="/" element={<Home c={archive.character} ch={archive.chapters}/>}/><Route path="/character" element={<Character c={archive.character}/>}/><Route path="/history" element={<History ch={archive.chapters}/>}/><Route path="/relationships" element={<Relationships r={archive.relationships}/>}/><Route path="/gallery" element={<Gallery c={archive.character} gallery={archive.gallery}/>}/><Route path="/admin" element={<AdminLogin/>}/><Route path="/admin/panel" element={<AdminGuard><AdminPanel archive={archive}/></AdminGuard>}/></Routes></Layout>}
const basename = import.meta.env.BASE_URL.replace(/\/$/, '');
createRoot(document.getElementById('root')).render(<BrowserRouter basename={basename}><App/></BrowserRouter>);
